name: Add Subdomain

on:
  push:
    branches:
      - main

jobs:
  add-subdomain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Add other steps relevant to your project here
      - name: Add Subdomains to Cloudflare
        run: |
          # Replace this with the actual command or script you need to run
          # For example, if you're using Python or another language, run the appropriate command
          # python ./scripts/update-dns.py
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
